spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oa513wuvaFeBpoMX4x6
            client-secret: 7tObPFL8sVt8HcFlBZlM1P2xZT2QExpujnR-0O0u
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: https://dev-668490-admin.okta.com/dev/console/oauth2/default